apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: proxy
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.local-cluster.internal"
  - port:
      number: 443
      name: tls
      protocol: HTTP
    hosts:
    - "*.local-cluster.internal"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-gateway-forwarding-poc
spec:
  hosts:
  - "test.local-cluster.internal"
  gateways:
  - proxy
  http:
  - match:
    - port: 80
      uri:
        prefix: /
    route:
    - destination:
        host: go-api-demo.playground.svc.cluster.local
        port:
          number: 80
