apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "restapi-testapp.labels" . | nindent 4 }}
  name: {{ include "restapi-testapp.fullname" .}}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
    {{- include "restapi-testapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "restapi-testapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: cjlapao/go-restapi-demo:latest
          imagePullPolicy: Always
          name: go-api-demo
          resources:
            requests: {cpu: "150m", memory: "25Mi"}
            limits: {cpu: "250m", memory: "50Mi"}
          env:
            - name: RESTAPI_API_PORT
              value: {{ .Values.ports.http | quote }}              
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
