apiVersion: v1
kind: Service
metadata:
    name: go-api-demo
    namespace: playground
    labels:
        app: go-api-demo
        environment: development
    annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
    type: ClusterIP
    ports:
        - protocol: TCP
          name: api
          port: 80
          targetPort: { { .Values.apiPort } }
    selector:
        app: go-api-demo
        environment: development
    sessionAffinity: None
