apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace.name}}
  name: {{include "restapi-testapp.fullname" .}}
  labels: {{- include "restapi-testapp.labels" . | nindent 4}}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: {{.Values.service.type}}
  ports:
    - protocol: TCP
      name: api
      port: {{.Values.service.port}}
      targetPort: {{.Values.apiPort}}
  selector: {{- include "restapi-testapp.selectorLabels" . | nindent 4}}
  sessionAffinity: None
