apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace.name}}
  name: {{include "restapi-testapp.fullname" .}}
  labels: {{- include "restapi-testapp.labels" . | nindent 4}}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: {{.Values.service.type}}
  ports:
    - protocol: TCP
      name: api-http
      port: {{.Values.service.http}}
      targetPort: {{.Values.ports.http}}
    {{- if .Values.ports.tlsEnabled }}
    - protocol: TCP
      name: api-tls
      port: {{.Values.service.tls}}
      targetPort: {{.Values.ports.tls}}
    {{- end }}
  selector: {{- include "restapi-testapp.selectorLabels" . | nindent 4}}
  sessionAffinity: None
